### ISSUE TITLE
Bug, Gray thing!

### ISSUE THREAD

**Issue by Arkodevlopr** [easonwong-de/Tab-Preview-On-Hover#10]
Hello, i was trying to use the extesion, but it doesn't work.
Take a look(Sorry for the another language on extension, i'm brazillian so i speak portuguese):
![Screenshot_2](https://github.com/easonwong-de/Tab-Preview-On-Hover/assets/157071696/55dbdff6-39f2-47f0-ad8c-755f5836ee18)
It says: Always can read and alter data on this site.
    -  Dykmn

**Comment by easonwong-de** [comment]
Ola, thanks for the report. The add-on being greyed out shouldn’t affect its functionality per se. When you hover your cursor over the tabs, does the floating panel show up? Or is the panel empty?

**Comment by XeonG** [comment]
its a bit broken in newer firefox 124  ..also does it show more than 12 tabs?

**Comment by easonwong-de** [comment]
@XeonG Thanks for the information, but the add-on is optimised to work on the current release version of Firefox, since the developer & nightly versions may not be the stablest to cope with.
As of the number of tabs that has the preview enabled, I put it to 10 because I found it optimal for performance reasons.
Since no specific issues are discussed here, I’ll close the thread for now. Feel free to open new issues if a specific one is found.

**Comment by XeonG** [comment]
what do you mean optimal for performance reasons? I use vivaldi aswel and that has same tab thumbnail preview working with 100 tabs... hoenstly it begs the question why mozilla so useless at adding decent features like this built with customization.. same with tab stacking that vivaldi has where all the tabs in a stack will show thumbnails aswel... I know its not you to blame just think more devs should be telling mozilla this) anywayy is it possible to change the limit manually I'd rather have that as its a bit pointless if I have loads of tabs like 10+ but all the rest are just the last 10th tab image... counter intuitive really
