### ISSUE TITLE
Preview Panel Obscured. CSS Update Needed.

### ISSUE THREAD

**Issue by DodoLeDev** [easonwong-de/Tab-Preview-On-Hover#11]
Hi!
Firstly, thanks for your great job! It finally adds something that I missed for so long! :heart:

However, it seems that there is a problem with the Nightly version of Firefox (version 124.0a1 as of now)

My tabs seem to react, but nothing shows!

https://github.com/easonwong-de/Tab-Preview-On-Hover/assets/59477313/abe2c566-f718-4ee8-89e3-de86746ff11d

After digging into the issue, it appears that there is a problem with something about themes only if I am in system theme, but still nothing in dark theme, while there is no errors in the developer console...
![image](https://github.com/easonwong-de/Tab-Preview-On-Hover/assets/59477313/d24f6bfc-ed22-486f-a110-1d7ab9c6658a)

P.S. : I have tried both in system and dark theme

**Comment by easonwong-de** [comment]
Hello! Welcome here.

The preview tab not showing up might be related to the CSS theme you are using. As far as I know, the use of [WaveFox](https://github.com/QNetITQ/WaveFox) can also cause the same issue. The reason is that the CSS property `clip-path` obscures the preview panel. I am pretty sure this is why the preview is blocked, as I can still see the shadow poking out.

The add-on is not compatible with the built-in browser themes “System theme – auto” and “Firefox Alpenglow”, as specified in [README.md](https://github.com/easonwong-de/Tab-Preview-On-Hover/blob/main/README.md#compromises).

**Comment by easonwong-de** [comment]
Hi. It turns out it’s an easy fix within the CSS theme.

You may update the CSS theme.
